# build environment
FROM node:12.16 as build

WORKDIR /tsf-app
ENV PATH /tsf-app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.0 -g --silent

COPY . ./
RUN npm run-script build

# production environment
FROM nginx:stable-alpine
COPY --from=build /tsf-app/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
