apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2020-05-07T02:26:47Z"
  generation: 9
  labels:
    app: tsf-app
  name: tsf-app
  namespace: default
  resourceVersion: "1919353"
  selfLink: /apis/apps/v1/namespaces/default/deployments/tsf-app
  uid: 3365c10a-900a-11ea-ae47-42010a98011b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tsf-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tsf-app
    spec:
      containers:
      - image: gcr.io/teacher-student-forum/tsf-app@sha256:04096d5e8121d8ef42fd5bf5a70bc745207953c8856e73a5789309f71e4f747b
        imagePullPolicy: IfNotPresent
        name: tsf-app-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-05-07T07:33:50Z"
    lastUpdateTime: "2020-05-07T07:33:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-07T02:26:47Z"
    lastUpdateTime: "2020-05-13T10:53:30Z"
    message: ReplicaSet "tsf-app-86696489" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
