apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2020-05-07T02:27:52Z"
  generation: 8
  labels:
    app: tsf-server
  name: tsf-server
  namespace: default
  resourceVersion: "1919635"
  selfLink: /apis/apps/v1/namespaces/default/deployments/tsf-server
  uid: 59ecd676-900a-11ea-ae47-42010a98011b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tsf-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tsf-server
    spec:
      containers:
      - image: gcr.io/teacher-student-forum/tsf-server@sha256:09271594c2831c432f8c0821a22cd9d58dff67f38682c7eaa5b4dc49b5ecbd10
        imagePullPolicy: IfNotPresent
        name: tsf-server-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-05-13T05:51:16Z"
    lastUpdateTime: "2020-05-13T05:51:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-07T02:27:52Z"
    lastUpdateTime: "2020-05-13T10:54:43Z"
    message: ReplicaSet "tsf-server-57cfff567b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
