apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudsql-proxy
spec:
  selector:
    matchLabels:
      app: cloudsql-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudsql-proxy
        unit: mycloudsql
    spec:
      containers:
        - name: tsf-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.16
          command: ["/cloud_sql_proxy","-instances=teacher-student-forum:australia-southeast1:teacher-student-forum=tcp:0.0.0.0:3306","-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDIR:
