use tsf;

CREATE TABLE IF NOT EXISTS forums
(
    id int NOT NULL AUTO_INCREMENT,
    name varchar(128) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);